name: "Deploy to vercel"

inputs:
  path:
    description: "The path to deploy"
    type: string
    required: false
    default: ""

outputs:
  vercel_deployment_url:
    description: "The deployment url"
    value: ${{ steps.deploy-to-vercel.outputs.vercel_deployment_url }}

runs:
  using: "composite"
  steps:
    - id: deploy-to-vercel
      shell: bash
      run: echo "vercel_deployment_url=$(vercel --cwd ${{ inputs.path }} deploy --prebuilt  --token=${{ env.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT
