packages:
  # all packages in subdirs of apps/ and packages/
  - 'apps/**'
  - 'packages/**'
  # exclude packages github actions
  - '!.github/**'
  # exclude packages in generated paths
  - '!**/.vercel/**'
