packages:
  # all project dirs
  - "design/**"
  - "framework/**"
  - "products/**"
  - "quality-assurance/**"
  # exclude packages github actions
  - "!.github/**"
  # - ".github/**"
  # exclude packages in generated paths
  - "!**/.vercel/**"
