type Task {
	title: String!
	description: String

	size: Int!
	priority: Int!
	businessValue: Int!
	dueDate: Time!

	schedule: String!
	done: Boolean!
	labels: [Label!] @relation
}

type Label {
	name: String!
	description: String
	tasks: [Task!] @relation
}

type Query {
	tasks: [Task!]
	findCurrentTask: Task @resolver(name: "findCurrentTask")
	findTasksByDueDate(fromDate: Time!, toDate: Time!): [Task] @resolver(name: "findTasksByDueDate")
	findTasksByLabel(labelID: ID!): [Task!] @resolver(name: "findTasksByLabel")

	labels: [Label!]
}
