#!/bin/bash

DEBUG=${DEBUG:-0}

initial_commit_rev=$(git rev-list --max-parents=0 HEAD 2>/dev/null)
current_tag_rev=$(git describe --tags --abbrev=0 --contains --match "$1" 2>/dev/null)
previous_tag_rev=$(git describe --tags --abbrev=0 ${current_tag_rev:+"--exclude" "$current_tag_rev"} --match "$1" 2>/dev/null)
previous_tag_child_rev=$(git rev-list --reverse --ancestry-path "$previous_tag_rev..HEAD" 2>/dev/null | head -n 1)
previous_commit_rev='HEAD^'

target_rev=${previous_tag_child_rev:-${initial_commit_rev:-$previous_commit_rev}}

since_previous_release=$(git diff --quiet HEAD "$VERCEL_GIT_PREVIOUS_SHA" "$2" ; echo $?)
since_previous_tag=$(git diff --quiet HEAD "$target_rev" "$2" ; echo $?)

if [ $DEBUG = "1" ]; then
  echo "initial_commit_rev:"
  echo "  command: git rev-list --max-parents=0 HEAD 2>/dev/null"
  echo "  result: $initial_commit_rev"
  echo ""

  echo "current_tag_rev:"
  echo "  command: git describe --tags --abbrev=0 --contains --match \"$1\" 2>/dev/null"
  echo "  result: $current_tag_rev"
  echo ""

  echo "previous_tag_rev:"
  echo "  command: git describe --tags --abbrev=0 ${current_tag_rev:+"--exclude" "$current_tag_rev"} --match \"$1\" 2>/dev/null"
  echo "  result: $previous_tag_rev"
  echo ""

  echo "previous_tag_child_rev:"
  echo "  command: git rev-list --reverse --ancestry-path \"$previous_tag_rev..HEAD\" 2>/dev/null | head -n 1"
  echo "  result: $previous_tag_child_rev"
  echo ""

  echo "target_rev:"
  echo "  command: \${previous_tag_child_rev:-\${initial_commit_rev:-\$previous_commit_rev}}"
  echo "  since_previous_tag: $target_rev"
  echo ""

  echo "result:"
  echo "  command: git diff --quiet HEAD \"$target_rev\" \"$2\" ; echo \$?"
  echo "  since_previous_release: $since_previous_release"
  echo "  command: git diff --quiet HEAD \"$target_rev\" \"$2\" ; echo \$?"
  echo "  since_previous_tag: $since_previous_tag"
fi

# The diff command fails when there are more than 10 commits since the previous release,
# in that case we always trigger a deployment
if [ "$since_previous_release" = "0" ] || [ "$since_previous_tag" = "0" ]; then
  exit 0
else
  exit 1
fi
