name: Install dependencies

inputs:
  install_command:
    description: "Command to install dependencies"
    type: string
    default: "pnpm install --frozen-lockfile"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: ${{ inputs.install_command }}
