query FindAllTasksAndLabels {
	tasks {
		data {
			_id
			title
			description
			size
			priority
			businessValue
			dueDate
			done
			labels {
				data {
					_id
				}
			}
		}
	}
	labels {
		data {
			_id
			name
			description
		}
	}
}
