mutation UpdateTask($id: ID!, $data: TaskInput!) {
	updateTask(id: $id, data: $data) {
		_id
		title
		description
		size
		priority
		businessValue
		dueDate
		done
		labels {
			data {
				_id
			}
		}
	}
}
