type Project {
	name: String!
	events: [Event!] @relation
}

type EventDetails @embedded {
	speed: String!
}

type Event {
	type: String!
	timestamp: Time!
	uri: String!
	page: String!
	details: EventDetails!
	project: Project! @relation
}

type Query {
	allProjects: [Project!]
	allEvents: [Event!]
}
