#!/bin/bash

with_env_arg="--with-env"

[[ $1 = "$with_env_arg" ]] \
  && with_env="1" \
  || with_env="0"

[[ $with_env = "1" ]] \
  && module="$2" \
  || module="$1"

[[ $with_env = "1" ]] \
  && command_args_start=3 \
  || command_args_start=2

[[ $with_env = "1" ]] \
  && command="build:env" \
  || command="build"

[[ -n $module ]] \
  && run_args=( "--filter" "@ovenwand/$module" ) \
  || run_args=()

turbo run "${run_args[@]}" "$command" -- "${@:$command_args_start}"