#!/bin/bash

initial_commit_ref=$(git rev-list --max-parents=0 HEAD 2>/dev/null)
previous_tag_ref=$(git describe --tags --abbrev=0 --match "$1" 2>/dev/null)
previous_commit_ref='HEAD^'

target_ref=${previous_tag_ref:-${initial_commit_ref:-$previous_commit_ref}}

git diff HEAD "$target_ref" --quiet "$2"
