name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Setup github action
        run: |
          pnpm install
          cd .github/actions/release && pnpm install --prod

      - name: Create or update pull request
        uses: ./.github/actions/release
        with:
          commit: 'ci: release'
          title: 'ci: release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
