name: Test

run-name: "Test (${{ github.event.deployment.environment }})"

on:
  deployment_status:

jobs:
  quality-gate-test-end-to-end:
    name: "Quality gate: Test end-to-end"
    if: github.event_name == 'deployment_status' && github.event.deployment.environment == 'Preview – ovenwand-com' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.35.0-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/common/environment/setup

      - name: Test end-to-end
        uses: ./.github/actions/jobs/test/test-end-to-end
        with:
          base_url: ${{ github.event.deployment_status.target_url }}

  publish-test-reports:
    name: "Publish: Test report"
    if: ${{ success() || failure() }}
    needs: [quality-gate-test-end-to-end]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/common/environment/setup

      - name: Deploy test report
        uses: ./.github/actions/jobs/test/deploy-test-report
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_QUALITY_ASSURANCE_REPORTS }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
