name: Test end-to-end

run-name: "Test end-to-end (${{ github.event.deployment.environment }})"

on:
  deployment_status:

jobs:
  quality-gate-test-end-to-end:
    name: "Quality gate: Test end-to-end"
    if: github.event.deployment.environment == 'Preview – ovenwand-com' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.35.0-jammy
      options: --user 1001
    outputs:
      test_result: ${{ steps.test-end-to-end.outcome }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/common/environment/setup

      - id: test-end-to-end
        name: Test end-to-end
        uses: ./.github/actions/jobs/test/test-end-to-end
        with:
          base_url: ${{ github.event.deployment_status.target_url }}

      - id: deploy-test-report
        name: Deploy test report
        if: ${{ success() || failure() }}
        uses: ./.github/actions/jobs/test/deploy-test-report
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_QUALITY_ASSURANCE_REPORTS }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
